# Generated by Django 2.0.2 on 2018-02-12 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180211_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='external_files/game_icons', validators=[django.core.validators.FileExtensionValidator]),
        ),
    ]
