# Generated by Django 2.0.2 on 2018-02-12 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180212_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='external_files/game_icons', validators=[django.core.validators.FileExtensionValidator(['.jpg', '.jpeg', '.png', '.gif'])]),
        ),
    ]
