# Generated by Django 2.0.2 on 2018-02-13 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180212_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
