# Generated by Django 2.0.2 on 2018-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180213_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
